# Generated by Django 3.1.3 on 2020-11-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djboot', '0002_studentinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentinfo',
            table='studentinfo',
        ),
    ]
